name: Update Quant-Pro Dashboard
on:
  schedule:
    - cron: '5 8 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # <--- Modificato da 3.9 a 3.10 per risolvere l'errore

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run Engine
        run: python quant_pro_engine.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Update Dashboard" || exit 0
          git push
